name:                gb
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- filepath
- directory
- containers
- digest
- free

- cereal
- bytestring
- vector
- primitive

- mtl
- lens

- text
- sdl2

- ansi-terminal

library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns

executables:
  gb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gb

tests:
  rom-test:
    main:               Spec.hs
    source-dirs:        testing
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gb
    - hspec
