name:                gb
version:             0.1.0.0
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2019 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

dependencies:
- base >= 4.7 && < 5
- containers

- bytestring
- vector
- primitive
- attoparsec

- mtl
- comonad
- lens
- sdl2


library:
  source-dirs: src
  ghc-options:
  - -fwarn-incomplete-patterns

executables:
  gb-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gb

tests:
  gb-rewrite-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gb-rewrite
